# Generated by Django 2.2.3 on 2020-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsapp', '0005_auto_20200407_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='atag',
            field=models.UUIDField(default='29884082b0104dff940460cc0c47211a', editable=False, unique=True),
        ),
    ]
