# Generated by Django 2.2.3 on 2020-04-07 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qsapp', '0006_auto_20200407_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='atag',
            field=models.UUIDField(default=uuid.UUID('6d53657c-99ad-46ef-838f-ee4d39607874'), editable=False, unique=True),
        ),
    ]
